### ISSUE TITLE
Weight file

### ISSUE THREAD

**Issue by OrkhanHI** [wangmiaowei/CVDancer_Classification#1]
Hi,

I can't find the weights file:

```
root_path = r'C:\Users\James\Documents\The project Miaowei Wang has done\Kaggle_NCFM-master\saved_models'
weights_path = os.path.join(root_path, 'weights2.h5')
```

**Comment by wangmiaowei** [comment]
Sorry We will upload the weight file ASAP.

**Comment by OrkhanHI** [comment]
Thank you, appreciate it.

**Comment by OrkhanHI** [comment]
Any updates on weight file?

**Comment by wangmiaowei** [comment]
Thanks for your patient. I have uploaded the downloading link in the README now
(
https://files.slack.com/files-pri/T01GJ9C2L7M-F01GT0H53TM/download/weights2.h5)

**Comment by wangmiaowei** [comment]
I will close this issue
